/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantalllasGarbage;

/**
 *
 * @author hanze
 */
public class PantallaCalificacion extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCalificacion
     */
    public PantallaCalificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntuaApp = new javax.swing.JLabel();
        cbxEstrellas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPuntuaApp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPuntuaApp.setText("Puntua la App");
        getContentPane().add(lblPuntuaApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cbxEstrellas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 ESTRELLAS", "4 ESTRELLAS", "3 ESTRELLAS", "2 ESTRELLAS ", "1 ESTRELLA ", "CESAR PONGAME 20" }));
        getContentPane().add(cbxEstrellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Agregue un comentario :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtComentario.setText("jTextField1");
        getContentPane().add(txtComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 60));

        btnSalir.setBackground(new java.awt.Color(204, 0, 51));
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCalificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxEstrellas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPuntuaApp;
    private javax.swing.JTextField txtComentario;
    // End of variables declaration//GEN-END:variables
}
