
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantalllasGarbage;

import javax.swing.DefaultListModel;
import garbageapp.Navegador;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Personal
 */
public class PantallaDistrito extends javax.swing.JFrame {
    
    DefaultListModel modeloLista = new DefaultListModel();
    List<Navegador> navegadores = new ArrayList<>();
    
    /**
     * Creates new form PantallaDistrito
     */
    public PantallaDistrito() {
        initComponents();
        listDistritos.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listDistritos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtNombreDistrito = new javax.swing.JTextField();
        btnBuscarDistrito = new javax.swing.JButton();
        btnSalirDistrito = new javax.swing.JButton();
        lblDistritos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listDistritos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nombre-Distrito-Poblacion-AreasSolidas", "Nombre-Distrito-Poblacion-AreasSolidas", "Nombre-Distrito-Poblacion-AreasSolidas", "Nombre-Distrito-Poblacion-AreasSolidas", "Nombre-Distrito-Poblacion-AreasSolidas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDistritos.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jScrollPane1.setViewportView(listDistritos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Distrito :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtNombreDistrito.setText("txttext1");
        txtNombreDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, -1));

        btnBuscarDistrito.setBackground(new java.awt.Color(153, 255, 255));
        btnBuscarDistrito.setText("Buscar");
        btnBuscarDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 100, 40));

        btnSalirDistrito.setBackground(new java.awt.Color(255, 51, 51));
        btnSalirDistrito.setText("Salir");
        getContentPane().add(btnSalirDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, 40));

        lblDistritos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDistritos.setText("Distrito");
        getContentPane().add(lblDistritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDistritoActionPerformed
        buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDistritoActionPerformed

    private void btnBuscarDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDistritoActionPerformed

        buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDistritoActionPerformed

    
    private void buscar() {
        modeloLista.removeAllElements();
        for(Navegador nav : navegadores)
        {
            if(nav.getNombre().toLowerCase()
                .contains(txtNombreDistrito.getText().toLowerCase())){
                modeloLista.addElement(nav.getNombre());
            }
        }
    }
    
    void actualizaLista(){
     modeloLista.removeAllElements();
     for(Navegador nav : navegadores)
     {
       modeloLista.addElement(nav.getNombre());
       
     }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new PantallaDistrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDistrito;
    private javax.swing.JButton btnSalirDistrito;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDistritos;
    private javax.swing.JList<String> listDistritos;
    private javax.swing.JTextField txtNombreDistrito;
    // End of variables declaration//GEN-END:variables
}
