/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantalllasGarbage;

/**
 *
 * @author hanze
 */
public class PantallaNormasyCondiciones extends javax.swing.JFrame {

    /**
     * Creates new form PantallaNormasyCondiciones
     */
    public PantallaNormasyCondiciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNormasyCondiciones = new javax.swing.JLabel();
        txtNormasyCondiciones = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNormasyCondiciones.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNormasyCondiciones.setText("NORMAS Y CONDICIONES");
        getContentPane().add(lblNormasyCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 350, 41));

        txtNormasyCondiciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNormasyCondiciones.setText("Normas y Condiciones");
        txtNormasyCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNormasyCondicionesActionPerformed(evt);
            }
        });
        getContentPane().add(txtNormasyCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 340, 220));

        btnAceptar.setBackground(new java.awt.Color(0, 255, 255));
        btnAceptar.setText("Aceptar");
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNormasyCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNormasyCondicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNormasyCondicionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaNormasyCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaNormasyCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaNormasyCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaNormasyCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaNormasyCondiciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel lblNormasyCondiciones;
    private javax.swing.JTextField txtNormasyCondiciones;
    // End of variables declaration//GEN-END:variables
}
