/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantalllasGarbage;

import javax.swing.JOptionPane;

/**
 *
 * @author omar_
 */
public class PantallaLogin extends javax.swing.JFrame {

    /**
     * Creates new form PantallaLogin
     */
    public PantallaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnEntrarLogin = new javax.swing.JButton();
        lblmail = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        txtContraseñaLogin = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Contraseña:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 40));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 255, 0));
        jButton2.setText("Crear Cuenta Nueva");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 140, 40));

        btnEntrarLogin.setBackground(new java.awt.Color(51, 51, 255));
        btnEntrarLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEntrarLogin.setForeground(new java.awt.Color(0, 0, 204));
        btnEntrarLogin.setText("Iniciar Sesión");
        btnEntrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarLoginMouseClicked(evt);
            }
        });
        btnEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 140, 40));

        lblmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmail.setForeground(new java.awt.Color(255, 255, 255));
        lblmail.setText("Usuario:");
        getContentPane().add(lblmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 20));
        getContentPane().add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, 30));
        getContentPane().add(txtContraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 300, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_login.PNG"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         PantallaCrearNuevaCuenta CNC = new PantallaCrearNuevaCuenta();
         CNC.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarLoginActionPerformed

    }//GEN-LAST:event_btnEntrarLoginActionPerformed

    private void btnEntrarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarLoginMouseClicked

        String Usuario = txtUsuarioLogin.getText();
        String Paswd = txtContraseñaLogin.getText();
        
        if(Usuario.isEmpty() || Paswd.isEmpty()){
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio");
            
        }else{
            if(Usuario.equals("Usuario") && Paswd.equals("1234")){
                JOptionPane.showMessageDialog(null, "Bienvenido");
                PantallaPrincipal PP = new PantallaPrincipal();
                PP.setVisible(true);
                this.dispose();
                
            }else
            {
                JOptionPane.showMessageDialog(null, "Su usuario o contraseña es incorrecto");
            }
        }
        
//        String Usuario= "admin";
//        String Contraseña= "123";
//        
//        String Pass = new String (txtContraseñaLogin.getPassword());
//        
//        if(txtUsuarioLogin.getText().equals(Usuario)&& Pass.equals(Contraseña)){
//            
//            PantallaPrincipal PP = new PantallaPrincipal();
//         PP.setVisible(true);
//         this.dispose();
//            
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(this, "Usuario  /  Contraseña Incorrecto");
//        }
                
// TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarLogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblmail;
    private javax.swing.JPasswordField txtContraseñaLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
