
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantalllasGarbage;

import javax.swing.DefaultListModel;
import garbageapp.Navegador;
import garbageapp.DistritoZonanueva;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Personal
 */
public class PantallaDistrito extends javax.swing.JFrame {
    
    DefaultListModel modeloLista = new DefaultListModel();
    List<Navegador> navegadores = new ArrayList<>();
    List<DistritoZonanueva> Distritozona = new ArrayList<>();
    String DatosLista;
    /**
     * Creates new form PantallaDistrito
     */
    
    public void Convertidor(){
        int tam = modeloLista.size();
        int count = 0;
        
        for(int=0;i<tam;i++)
        {
            Distritozona.get(i).
            
        }
        
            
    }
    
    

    public PantallaDistrito() {
        initComponents();
        listDistritos.setText(DatosLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listDistritos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtNombreDistrito = new javax.swing.JTextField();
        btnBuscarDistrito = new javax.swing.JButton();
        btnSalirDistrito = new javax.swing.JButton();
        lblDistritos = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listDistritos.setColumns(20);
        listDistritos.setRows(5);
        getContentPane().add(listDistritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 180));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Distrito :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtNombreDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, -1));

        btnBuscarDistrito.setBackground(new java.awt.Color(153, 255, 255));
        btnBuscarDistrito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarDistrito.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDistrito.setText("Buscar");
        btnBuscarDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 100, 40));

        btnSalirDistrito.setBackground(new java.awt.Color(255, 51, 51));
        btnSalirDistrito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalirDistrito.setForeground(new java.awt.Color(255, 0, 0));
        btnSalirDistrito.setText("Salir");
        btnSalirDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 40));

        lblDistritos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDistritos.setForeground(new java.awt.Color(255, 255, 255));
        lblDistritos.setText("Distrito");
        getContentPane().add(lblDistritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setText("Agregar Zona");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_distrito.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDistritoActionPerformed
        buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDistritoActionPerformed

    private void btnBuscarDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDistritoActionPerformed

        buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDistritoActionPerformed

    private void btnSalirDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDistritoActionPerformed
         PantallaPrincipal PP5 = new PantallaPrincipal();
         PP5.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnSalirDistritoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        PantallaAgregarZonaNueva PAZ6 = new PantallaAgregarZonaNueva(this);
        PAZ6.setLocationRelativeTo(null);
        PAZ6.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void buscar() {
        modeloLista.removeAllElements();
        for(Navegador nav : navegadores)
        {
            if(nav.getNombre().toLowerCase()
                .contains(txtNombreDistrito.getText().toLowerCase())){
                modeloLista.addElement(nav.getNombre());
            }
        }
    }
    
    void actualizaLista(){
     modeloLista.removeAllElements();
     for(Navegador nav : navegadores)
     {
       modeloLista.addElement(nav.getNombre());
       
     }  
    }
    
    void setDistritoZonanueva(DistritoZonanueva distritoZonanueva){
        Distritozona.add(distritoZonanueva);
        navegadores.add(distritoZonanueva);
        actualizaLista();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new PantallaDistrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDistrito;
    private javax.swing.JButton btnSalirDistrito;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDistritos;
    private javax.swing.JTextArea listDistritos;
    private javax.swing.JTextField txtNombreDistrito;
    // End of variables declaration//GEN-END:variables
}
